### ISSUE TITLE
Name Lookup Fails

### ISSUE THREAD

**Issue by Yampanis** [jhpoelen/cal-sailing-cam#2]
We wiped the OS from the local workstation, is there a host entry needed to reach the Pi..?

csc@csc-Z97M-D3H:~$ ssh pi@raspberrypi.local
ssh: Could not resolve hostname raspberrypi.local: Name or service not known

**Comment by jhpoelen** [comment]
no host entry should be needed because zeroconf is used.  google "avahi zeroconf raspberry pi" for more information about this and ensure that this is enabled on local workstation. Please close issue if this resolves the issue, if not, please comment with more details.

**Comment by Yampanis** [comment]
O.K. just saving few troubleshooting commands to try later on the local workstation...

$ service avahi-dnsconfd status

$avahi-discover

$avahi-resolve -4 --name raspberrypi.local

$ ping raspberrypi.local

**Comment by Yampanis** [comment]
here are results... looks like it needs to be installed..?

csc@csc-Z97M-D3H:~$ service avahi-dnsconfd status
● avahi-dnsconfd.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

csc@csc-Z97M-D3H:~$ avahi-discover
The program 'avahi-discover' is currently not installed. To run 'avahi-discover' please ask your administrator to install the package 'avahi-discover'

csc@csc-Z97M-D3H:~$ ping raspberrypi.local
ping: unknown host raspberrypi.local
csc@csc-Z97M-D3H:~$ avahi-resolve -4 --name raspberrypi.local
Failed to resolve host name 'raspberrypi.local': Timeout reached
csc@csc-Z97M-D3H:~$

**Comment by jhpoelen** [comment]
Yep, sounds like it is not installed yet.

**Comment by Yampanis** [comment]
OK... should be part of the Ubuntu default installation, but i'll try entering the following...

sudo apt-get install avahi-daemon
sudo update-rc.d avahi-daemon defaults
sudo /etc/init.d/avahi-daemon restart

**Comment by Yampanis** [comment]
Apparently it was there all along.  Huh.  Not sure what to try next...?

admin@csc-Z97M-D3H:~$ sudo apt-get install avahi-daemon
[sudo] password for admin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
avahi-daemon is already the newest version (0.6.32~rc+dfsg-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 106 not upgraded.
admin@csc-Z97M-D3H:~$ sudo update-rc.d avahi-daemon defaults
admin@csc-Z97M-D3H:~$ sudo /etc/init.d/avahi-daemon restart
[ ok ] Restarting avahi-daemon (via systemctl): avahi-daemon.service.
admin@csc-Z97M-D3H:~$ ssh pi@raspberrypi.local
ssh: Could not resolve hostname raspberrypi.local: Name or service not known
admin@csc-Z97M-D3H:~$

**Comment by jhpoelen** [comment]
interesting. Did you check that the pi and the workstation are on the same network?

**Comment by Yampanis** [comment]
Well, both are getting data from the Internet through the same modem/DSL.  Although the light on the pi nic is yellow.

**Comment by Yampanis** [comment]
what about the other Pi attached to the video cameras..?  does that one use avahi that we could use as a test..?

**Comment by jhpoelen** [comment]
Ah. I thought you were testing with the webcam pi. If not, you have to check whether the pi has avahi installed. Just google "avahi raspberrypi zeroconf" or similar. If this doesn't work, I have a look next time I am at cal sailing.

**Comment by Yampanis** [comment]
Sorry, my fault for the confusion, i forgot there was two pis.  In any case, the ssh is not working for the webcam pi, so there must be some misconfiguration.  The fact that avahi shows as installed, but returns a status of inactive (dead) must be a clue.

**Comment by Alkeryn** [comment]
I had the same issue
I then succed to connect like this
$ifconfig
find the raspberry interface and copy the inet6 adress, for me the interface was enp0s20u3 and the adress fe80::584d:74ea:8df8:22e
$ssh -6 pi@fe80::584d:74ea:8df8:22e%enp0s20u3

-6 force ssh to use ipv6
enp0... is the interface of the pi that you have to specify because each interface have ipv6 adress begining with fe80

**Comment by jhpoelen** [comment]
@Alkeryn thanks for chiming in . Would you be willing to troubleshoot at the club house?

**Comment by Alkeryn** [comment]
Yeah why not 

actually i found a better way because ifconfig don't give the correct adress (i made a mistake sorry)
do an avahi-browse --all
then find your raspbery pi
then avahi-resolve -n raspberrypi.local
copy the ipv6 adress and then 
ssh -6 pi@fe80::584d:74ea:8df8:22e%enp0s20u3
Where fe80::584d:74ea:8df8:22e is the ipv6 avahi gave you (ifconfig don't give the right one )
and enp0s20u3is the interface

**Comment by Alkeryn** [comment]
So the pro is now you can ssh to your raspi 0 
the con is that you have to do it almost each time

**Comment by jhpoelen** [comment]
Closing stale issue.
