### ISSUE TITLE
Raspberry Pi in the club house has expired root cert

### ISSUE THREAD

**Issue by MrMinos** [jhpoelen/cal-sailing-cam#3]
This causes `curl` to throw error when the script is run to upload the images.

A temporary solution is to use `--insecure` option. More permanent solution is to update the root certificates on the pi, however when tried today in the clubhouse, the distro was so old that it could not `apt-get upgrade`.

Troubleshooted this with @jhpoelen!

**Comment by jhpoelen** [comment]
@MrMinos thanks for helping to troubleshoot this funny issue. 

Before your pull request, it looked like this (see attached image) -

![Screenshot from 2021-10-03 07-33-34](https://user-images.githubusercontent.com/1084872/135758552-b26eebff-8836-44fa-8cb4-a3c27663ee22.png)

**Comment by MrMinos** [comment]
It worked! 🎉  
We might need to do a bit more troubleshooting for the dock cam. It seems like it has not yet updated or is unresponsive from the pi.

![Screen Shot 2021-10-03 at 08 46 13](https://user-images.githubusercontent.com/7379390/135761513-08278489-a2ca-469a-b66c-c98b1ace1933.png)

**Comment by jhpoelen** [comment]
@MrMinos good stuff! Thanks for making this work!

Hmm. That dock cam does look kinda weird. That is the one with the funky hack for dealing with the ancient video stream format. You should be able to troubleshoot remotely by inspecting / adjusting the log upload to https://whatskraken.cal-sailing.org/cam/log . 

Perhaps retrieving the image from the dock cam is taking so long that the process gets killed as part of the next update. . .

**Comment by jhpoelen** [comment]
ps @MrMinos you should be able to count your work on this web cam stuff towards your work hours at cal-sailing.

**Comment by MrMinos** [comment]
```
root      2157     1  0 Oct02 tty4     00:00:00 /sbin/getty 38400 tty4
root      2158     1  0 Oct02 tty5     00:00:00 /sbin/getty 38400 tty5
root      2159     1  0 Oct02 tty6     00:00:00 /sbin/getty 38400 tty6
root      2160     1  0 Oct02 ?        00:00:00 /sbin/getty -L ttyAMA0 115200 vt100
root      2558     2  0 12:47 ?        00:00:02 [kworker/0:0]
root      4909  1874  0 15:35 ?        00:00:00 /USR/SBIN/CRON
pi        4910  4909  0 15:35 ?        00:00:00 /bin/sh -c sh -c "`curl -L --silent https://raw.github.com/jhpoelen/cal-sailing-cam/master/update_cam.sh`" >> /home/pi/update_cam.log 2>&1
pi        4919  4910  0 15:35 ?        00:00:00 sh -c #!/bin/sh  SERVER_URL="https://whatskraken.cal-sailing.org" UPLOAD_URL="$SERVER_URL/cam"  CURL="curl --max-time 15 --insecure"  update_cam() { ?echo `date` update cam [$2] starting...         $CURL --globoff "http://$1/img/snapshot.cgi?[size=3][&quality=3]" | curl --insecure -F $2=@- -v $UPLOAD_URL ?echo `date` update cam [$2] done. }  update_trendnet_tv_ip110w_a() {         # Trendnet TV-IP110W/A ?echo `date` update cam [$2] starting...         #curl -u 'admin:admin' --globoff "http://$1/admin/view.cgi?profile=2" | curl -F $2=@- -v $UPLOAD_URL         STREAM_CHUNK=$2-1M.mjpeg         curl "http://$1/cgi/mjpg/mjpeg.cgi" | head -c1048576 > $STREAM_CHUNK          avconv -i "$STREAM_CHUNK" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL         rm $2-1M.mjpeg ?echo `date` update cam [$2] done. }  update_hd_cam() {         echo `date` update cam [$2] starting...         avconv -i "rtsp://$1:554" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL         echo `date` update cam [$2] done. }  update_whiteboard_lowres_cam() { ?echo `date` update cam [$2] starting... ?avconv -i "rtsp://$1:554/user=admin&password=&channel=1&stream=1.sdp?real_stream--rtp-caching=100" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL ?echo `date` update cam [$2] done. }  upload_logs() {   # upload list of running pi processes   ps -ef | $CURL -F log=@- -v $UPLOAD_URL    # upload list of processes to be killed   local REGEX="curl -F dock="   ps -e | grep "$REGEX" | sed -E 's/^\s+//g' | $CURL -F log_kill=@- -v $UPLOAD_URL    # attempt to cleanup stale avconv processes   #ps -e | grep "$REGEX" | sed -E 's/^\s+//g' | cut -d ' ' -f1 | xargs -L1 kill  }  curl --insecure $SERVER_URL/ping  upload_logs  update_hd_cam 192.168.1.10 restaurant  #update_cam 192.168.1.253 dock update_trendnet_tv_ip110w_a 192.168.1.210 dock  update_whiteboard_lowres_cam 192.168.1.12 whiteboard
pi        4940  4919  0 15:35 ?        00:00:00 curl http://192.168.1.210/cgi/mjpg/mjpeg.cgi
pi        4941  4919  0 15:35 ?        00:00:00 head -c1048576
root      4946     2  0 15:35 ?        00:00:00 [kworker/u:2]
root      4958  1874  0 15:36 ?        00:00:00 /USR/SBIN/CRON
pi        4960  4958  0 15:36 ?        00:00:00 /bin/sh -c sh -c "`curl -L --silent https://raw.github.com/jhpoelen/cal-sailing-cam/master/update_cam.sh`" >> /home/pi/update_cam.log 2>&1
pi        4968  4960  0 15:36 ?        00:00:00 sh -c #!/bin/sh  SERVER_URL="https://whatskraken.cal-sailing.org" UPLOAD_URL="$SERVER_URL/cam"  CURL="curl --max-time 15 --insecure"  update_cam() { ?echo `date` update cam [$2] starting...         $CURL --globoff "http://$1/img/snapshot.cgi?[size=3][&quality=3]" | curl --insecure -F $2=@- -v $UPLOAD_URL ?echo `date` update cam [$2] done. }  update_trendnet_tv_ip110w_a() {         # Trendnet TV-IP110W/A ?echo `date` update cam [$2] starting...         #curl -u 'admin:admin' --globoff "http://$1/admin/view.cgi?profile=2" | curl -F $2=@- -v $UPLOAD_URL         STREAM_CHUNK=$2-1M.mjpeg         curl "http://$1/cgi/mjpg/mjpeg.cgi" | head -c1048576 > $STREAM_CHUNK          avconv -i "$STREAM_CHUNK" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL         rm $2-1M.mjpeg ?echo `date` update cam [$2] done. }  update_hd_cam() {         echo `date` update cam [$2] starting...         avconv -i "rtsp://$1:554" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL         echo `date` update cam [$2] done. }  update_whiteboard_lowres_cam() { ?echo `date` update cam [$2] starting... ?avconv -i "rtsp://$1:554/user=admin&password=&channel=1&stream=1.sdp?real_stream--rtp-caching=100" -f image2 -frames:v 1 pipe:1 | curl --insecure -F $2=@- -v $UPLOAD_URL ?echo `date` update cam [$2] done. }  upload_logs() {   # upload list of running pi processes   ps -ef | $CURL -F log=@- -v $UPLOAD_URL    # upload list of processes to be killed   local REGEX="curl -F dock="   ps -e | grep "$REGEX" | sed -E 's/^\s+//g' | $CURL -F log_kill=@- -v $UPLOAD_URL    # attempt to cleanup stale avconv processes   #ps -e | grep "$REGEX" | sed -E 's/^\s+//g' | cut -d ' ' -f1 | xargs -L1 kill  }  curl --insecure $SERVER_URL/ping  upload_logs  update_hd_cam 192.168.1.10 restaurant  #update_cam 192.168.1.253 dock update_trendnet_tv_ip110w_a 192.168.1.210 dock  update_whiteboard_lowres_cam 192.168.1.12 whiteboard
pi        4972  4968  0 15:36 ?        00:00:00 ps -ef
pi        4973  4968  0 15:36 ?        00:00:00 curl --max-time 15 --insecure -F log=@- -v https://whatskraken.cal-sailing.org/cam
root      8636     2  0 Oct02 ?        00:00:00 [kworker/0:1]
```
> Perhaps retrieving the image from the dock cam is taking so long that the process gets killed as part of the next update. . .

Dead on. We can see the script runs again while the dock cam download (maybe hanged?) is in-flight.

**Comment by jhpoelen** [comment]
(from https://github.com/jhpoelen/cal-sailing-cam/commit/6e86ff2dff615fd02692795596bf70fa1715c2e4#commitcomment-57450311) it appears that the issue has been resolved after I reduced the amount of bits to sample from the mjpeg stream. Instead of reading about 1MB from the stream, now, only 128kB are read. See https://github.com/jhpoelen/cal-sailing-cam/commit/4d937f62aa32319313d89d6f431fede90ebdff88 . So, for some reason, the connection between the pi and the webcam got slower / stuck, at least slow enough for the connection to timeout and crap out. 

See attached screenshot of wind webpage. 

![Screenshot from 2021-10-03 19-52-57](https://user-images.githubusercontent.com/1084872/135786376-aa4d0d70-6476-489f-ba89-5ad227b37175.png)

@MrMinos now that a workaround for the root cert exists and the image are flowing again, how do you feel about the current setup? More work needed (e.g., upgrade, replacement etc)?

**Comment by MrMinos** [comment]
@jhpoelen That is great! Thank you for doing that. I think we can close this issue now.

> So, for some reason, the connection between the pi and the webcam got slower / stuck, at least slow enough for the connection to timeout and crap out. [...] how do you feel about the current setup? More work needed (e.g., upgrade, replacement etc)?

I think the next time pi fails, we could replace it with a pi Zero W version which should have enough compute power to drive all workflows we have, and is cost efficient at only $10.

**Comment by jhpoelen** [comment]
@MrMinos thanks for sharing your ideas. Am closing this issue.

In the past, wireless connections at the club have been a bit mwah - wired ethernet has proven to be a little more sturdy. Any way to shove an ethernet cable into a Pi Zero ?

**Comment by MrMinos** [comment]
Yes.. unfortunately, pi Zeros doesn't have a native ethernet port. We could go with the 3B or 4 full sized boards instead for the onboard ethernet option. Hopefully, the current fix is good for another few years 🤞

Thanks again, glad the cam setup is back up!
